title: UMDVDB
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

collections:
    umd-roms:
      permalink: "/:collection/:path"
      output: true

just_the_docs:
  collections:
    umd-roms:
      name: UMD-ROMs
